# Backup and fix profile only if it fails to parse; installs a minimal safe prompt
$ErrorActionPreference='Stop'
$prof = $PROFILE
if (-not (Test-Path $prof)) { Write-Host "[CoProfile-Guard] No profile found. Nothing to do." -ForegroundColor Green; exit 0 }

# AST parse check
$tok=[System.Management.Automation.Language.Token[]]$null
$err=[System.Management.Automation.Language.ParseError[]]$null
[System.Management.Automation.Language.Parser]::ParseFile($prof,[ref]$tok,[ref]$err) | Out-Null

if ($err -and $err.Count -gt 0) {
  $stamp = Get-Date -Format 'yyyyMMdd_HHmmss'
  $bak   = "$prof.bad_$stamp"
  Move-Item -LiteralPath $prof -Destination $bak -Force
  $safe = @"
# Minimal safe profile generated by CoProfile-Guard
function global:prompt { "PS $((Get-Location))> " }
# (BPOE disabled here; re-enable deliberately after repairs.)
"@
  [IO.File]::WriteAllText($prof,$safe,[Text.UTF8Encoding]::new($true))
  Write-Host "[CoProfile-Guard] Profile had parse errors; moved to:`n  $bak`nInstalled a minimal safe profile." -ForegroundColor Yellow
} else {
  Write-Host "[CoProfile-Guard] Profile parses clean; no change." -ForegroundColor Green
}