
name: Corpus Ingest
on:
  schedule: [{cron: "17 2 * * *"}]
  workflow_dispatch: {}
jobs:
  collect:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: pip install feedparser python-dateutil requests markdownify
      - name: Compose weekly brief
        run: |
          python CoCache/scripts/compose_weekly.py --ingest CoCache/ingest --out CoCache/synth/weekly_summaries
      - name: Prepare PRs
        run: |
          python CoCache/scripts/triage_and_raise.py --week latest --rickpublic RickPublic --CoSteward CoSteward
      - name: Commit summary (if any changes)
        run: |
          git config user.name "CoCivium Bot"
          git config user.email "bot@cocivium"
          git add -A
          git commit -m "chore(corpus): weekly brief" || true
          git push || true

