name: bpoe-self-evolve
on:
  workflow_call: {}
  schedule:
    - cron: "13 4 * * *"
permissions: { contents: write }
jobs:
  evolve:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup PowerShell
        uses: PowerShell/PowerShell@v1
        with: { version: "7.4.x" }
      - name: Refresh assets manifest
        shell: pwsh
        run: |
          Import-Module "$PWD/module/BPOE.Autopilot/BPOE.Autopilot.psd1"
          Invoke-BPOEAssetsManifest -Repo $PWD
      - name: Update SESSION_STATUS
        shell: pwsh
        run: |
          $stamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss K"
          @"
# Session Status
- Updated: $stamp
- Branch: $(git rev-parse --abbrev-ref HEAD 2>$null)
- Commit: $(git rev-parse --short HEAD 2>$null)
"@ | Set-Content -Path docs/bpoe/SESSION_STATUS.md -Encoding UTF8
      - name: Commit (gated by ENABLE_AUTOCOMMITS)
        shell: bash
        run: |
          set -e
          echo "ENABLE_AUTOCOMMITS=${{ vars.ENABLE_AUTOCOMMITS }}"
          if [ "${{ vars.ENABLE_AUTOCOMMITS }}" = "true" ]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add -A
            git diff --cached --quiet || (git commit -m "auto: self-evolve refresh" && git push)
          else
            echo "Auto-commits disabled; set repo variable ENABLE_AUTOCOMMITS=true to enable."
          fi

