name: bpoe-smoke
on:
  workflow_call:
    inputs:
      fail_external:
        required: false
        type: boolean
        default: false
jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup PowerShell
        uses: actions/setup-powershell@v2
        uses: PowerShell/PowerShell@v1
        with: { version: "7.4.x" }
      - name: Repo smoke (markdown + images)
        shell: pwsh
        run: |
          Import-Module "$PWD/module/BPOE.Autopilot/BPOE.Autopilot.psd1"
          Test-BPOERepoSmoke -Repo $PWD @(if ("${{ inputs.fail_external }}" -eq "true") { "-FailOnExternalLinks" })
