name: CoCivium Safety Checks

on:
  push:
  pull_request:

jobs:
  bn_name_guard:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Ensure "Being Noname" exact phrase exists in canonical file
        run: |
          set -euo pipefail
          file="Insights/BN_Story_being-noname_v1.0.md"
          if [[ -f "$file" ]]; then
            if ! grep -qiE '\bBeing[[:space:]]+Noname\b' "$file"; then
              echo "Expected exact phrase 'Being Noname' not found in $file"
              exit 1
            fi
          else
            echo "Canonical BN file not present; skipping check."
