name: Repo hygiene
on:
  push: { branches: [ main ] }
  schedule: [{ cron: "27 4 * * 1" }]
jobs:
  hygiene:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: actionlint
        uses: raven-actions/actionlint@v1
      - name: hygiene scan
        shell: pwsh
        run: pwsh ops/hygiene/Scan-And-Stage.ps1 -Autofix -DaysBeforePurge 30
      - name: commit staged fixes
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          if ! git diff --quiet; then
            git add -A
            git commit -m "chore(hygiene): deprecations/purge/size guard"
            git push
          fi

